/** Ключи admin-UI (ru-первичны; перевод расширяется ключами `en.*`). */

export const STRINGS = {
  'nav.dashboard': 'Обзор',
  'nav.sites': 'Сайты',
  'nav.pages': 'Страницы',
  'nav.contents': 'Контент',
  'nav.assets': 'Ассеты',
  'nav.routes': 'Роуты',
  'nav.forms': 'Формы',
  'nav.snapshots': 'Снапшоты',
  'nav.builds': 'Публикация',
  'nav.settings': 'Настройки',

  'page.overview': 'Обзор',
  'page.overview.empty': 'Выберите объект в меню слева',

  'common.loading': 'Загрузка…',
  'common.error': 'Ошибка',
  'common.reload': 'Обновить',
  'common.close': 'Закрыть',
  'common.create': 'Создать',
  'common.cancel': 'Отмена',
  'common.delete': 'Удалить',
  'common.confirm': 'Подтвердить',
  'common.actions': 'Действия',
  'common.empty': 'Пока пусто',
  'common.required': 'Обязательно',

  'site.title': 'Сайты',
  'site.new': 'Создать сайт',
  'site.name': 'Название',
  'site.slug': 'Slug',
  'site.locale': 'Язык по умолчанию',
  'site.hosts': 'Хосты',
  'site.none': 'Сайтов пока нет',
  'site.open': 'Открыть',
  'site.delete.confirm': 'Удалить сайт',
  'site.notFound': 'Сайт не найден',
  'site.sections': 'Разделы',

  'page.title': 'Страницы',
  'page.new': 'Создать страницу',
  'page.name': 'Название',
  'page.slug': 'Slug',
  'page.version': 'Версия',
  'page.none': 'Страниц пока нет',
  'page.open': 'Открыть',
  'page.delete.confirm': 'Удалить страницу',
  'page.editor.placeholder': 'Редактор дерева — в разработке (M1).',

  'content.title': 'Контент',
  'content.new': 'Создать item',
  'content.collection': 'Коллекция',
  'content.collection.all': 'Все коллекции',
  'content.id': 'ID',
  'content.fields': 'Поля',
  'content.fieldKey': 'Ключ',
  'content.fieldType': 'Тип',
  'content.fieldValue': 'Значение',
  'content.open': 'Открыть',
  'content.none': 'Контента пока нет',
  'content.delete.confirm': 'Удалить item',
  'content.base': 'Базовые поля',
  'content.baseHint': 'Язык по умолчанию ({locale}) — база для остальных локлей',
  'content.translations': 'Переводы',
  'content.addLocale': 'Добавить локаль',
  'content.locale': 'Локаль',
  'content.noTranslations': 'Переводов ещё нет',
  'content.save': 'Сохранить поля',
  'content.saved': 'Сохранено',
  'content.deleteTranslation.confirm': 'Удалить перевод',
  'content.invalidJson': 'Поле "{key}": невалидный JSON',
  'content.createError': 'Ошибка создания: {detail}',
  'content.addField': 'Добавить поле',
  'content.type.string': 'строка',
  'content.type.number': 'число',
  'content.type.boolean': 'bool',
  'content.type.json': 'json',

  'assets.title': 'Ассеты',
  'assets.upload': 'Загрузить',
  'assets.uploading': 'Загрузка…',
  'assets.file': 'Файл',
  'assets.name': 'Название',
  'assets.type': 'Тип',
  'assets.size': 'Размер',
  'assets.none': 'Ассетов пока нет',
  'assets.open': 'Открыть файл',
  'assets.delete.confirm': 'Удалить ассет',
  'assets.uploadError': 'Ошибка загрузки: {detail}',
  'assets.picker.title': 'Библиотека ассетов',
  'assets.picker.search': 'Поиск',
  'assets.select': 'Выбрать ассет',
  'assets.clear': 'Сбросить',

  'route.title': 'Роуты',
  'route.new': 'Создать роут',
  'route.matcher': 'Matcher (regex)',
  'route.priority': 'Приоритет',
  'route.action': 'Действие',
  'route.action.renderPage': 'Показ страницы',
  'route.action.serveAsset': 'Выдача ассета',
  'route.action.redirect': 'Редирект',
  'route.target': 'Цель',
  'route.none': 'Роутов пока нет',
  'route.delete.confirm': 'Удалить роут',
  'route.back': 'К списку роутов',
  'route.edit': 'Редактировать',
  'route.save': 'Сохранить',
  'route.saved': 'Сохранено',
  'route.errors.matcherRequired': 'Укажите matcher',
  'route.errors.matcherRegex': 'Matcher — невалидный regex',
  'route.errors.targetRequired': 'Укажите цель',
  'route.errors.statusRequired': 'redirect: выберите код ответа',
  'route.redirect.status': 'Код ответа',
  'route.redirect.keepQuery': 'Сохранить query',
  'route.warnings.duplicate': 'Matcher совпадает с существующим роутом',
  'route.warnings.prefix': 'Matcher пересекается с роутом {matcher}',

  'richText.toolbar.bold': 'Жирный',
  'richText.toolbar.italic': 'Курсив',
  'richText.toolbar.strike': 'Зачёркнутый',
  'richText.toolbar.code': 'Инлайн-код',
  'richText.toolbar.h1': 'Заголовок H1',
  'richText.toolbar.h2': 'Заголовок H2',
  'richText.toolbar.h3': 'Заголовок H3',
  'richText.toolbar.bulletList': 'Маркированный список',
  'richText.toolbar.orderedList': 'Нумерованный список',
  'richText.toolbar.blockquote': 'Цитата',
  'richText.toolbar.codeBlock': 'Блок кода',
  'richText.toolbar.hr': 'Разделитель',
  'richText.toolbar.link': 'Ссылка',
  'richText.toolbar.image': 'Изображение',
  'richText.link.placeholder': 'URL ссылки',
  'richText.link.apply': 'OK',
  'richText.slash.hint': '/ для команд',
  'richText.slash.noMatch': 'Нет команд для «{query}»',

  'form.title': 'Формы',
  'form.new': 'Создать форму',
  'form.name': 'Название',
  'form.formId': 'ID формы',
  'form.formIdHint': 'ID сгенерируется как form.<slug из названия>',
  'form.fields': 'Поля',
  'form.none': 'Форм пока нет',
  'form.open': 'Открыть',
  'form.delete.confirm': 'Удалить форму',
  'form.save': 'Сохранить форму',
  'form.saved': 'Сохранено',
  'form.definition': 'Определение (JSON)',
  'form.invalid': 'Ошибка определения',
  'form.back': 'К списку форм',
  'form.submissions': 'Сабмиты',
  'form.submissions.none': 'Сабмитов пока нет',
  'form.submissions.id': 'ID',
  'form.submissions.date': 'Дата',
  'form.submissions.payload': 'Полезная нагрузка',

  'editor.title': 'Редактор',
  'editor.undo': 'Назад',
  'editor.redo': 'Вперёд',
  'editor.addChild': 'Добавить',
  'editor.delete': 'Удалить',
  'editor.up': 'Вверх',
  'editor.down': 'Вниз',
  'editor.props': 'Свойства',
  'editor.selectHint': 'Выберите узел в дереве',
  'editor.unknownType': 'Неизвестный тип: {type}',
  'editor.tree': 'Дерево',
  'editor.canvas': 'Канвас',
  'editor.saveNow': 'Сохранить',
  'editor.saved': 'Сохранено, v{version}',
  'editor.dirty': 'Есть несохранённые изменения',
  'editor.saving': 'Сохранение…',
  'editor.saved.failed': 'Не удалось сохранить',
  'editor.binding': 'Источник',
  'editor.binding.path': 'Путь к данным',
  'editor.binding.literal': 'Литерал',
  'editor.binding.content': 'Контент',
  'editor.binding.route': 'Роут',
  'editor.binding.query': 'Параметры запроса',
  'editor.binding.operation': 'Операция',
  'editor.binding.form': 'Форма',
  'field.error.type': 'Неверный тип значения',
  'field.error.enum': 'Значение не из списка',
  'field.error.range': 'Вне диапазона',

  'canvas.design': 'Дизайн',
  'canvas.preview': 'Превью',
  'preview.build': 'Собрать превью',
  'preview.building': 'Сборка…',
  'preview.ready': 'Превью готово',
  'preview.failed': 'Ошибка сборки: {error}',
  'preview.empty': 'Соберите превью, чтобы видеть опубликованную страницу',
  'preview.open': 'Открыть в новой вкладке',
  'preview.refresh': 'Обновить превью',

  'op.listSites': 'Список сайтов',
  'op.createSite': 'Создать сайт',
  'op.getSite': 'Информация о сайте',
  'op.updateSite': 'Обновить сайт',
  'op.deleteSite': 'Удалить сайт',
  'op.createPage': 'Создать страницу',
  'op.listPages': 'Список страниц',
  'op.getPage': 'Страница',
  'op.saveTree': 'Сохранение дерева',
  'op.deletePage': 'Удалить страницу',
  'op.listContents': 'Список контента',
  'op.getContent': 'Контент',
  'op.createContent': 'Создать контент',
  'op.updateContent': 'Обновить контент',
  'op.deleteContent': 'Удалить контент',
  'op.putTranslation': 'Перевод сохранён',
  'op.deleteTranslation': 'Перевод удалён',
  'op.listAssets': 'Список ассетов',
  'op.uploadAsset': 'Загрузка ассета',
  'op.getAsset': 'Ассет',
  'op.deleteAsset': 'Удалить ассет',
  'op.listRoutes': 'Список роутов',
  'op.getRoute': 'Роут',
  'op.createRoute': 'Создать роут',
  'op.updateRoute': 'Обновить роут',
  'op.deleteRoute': 'Удалить роут',
  'op.listForms': 'Список форм',
  'op.createForm': 'Создать форму',
  'op.getForm': 'Форма',
  'op.updateForm': 'Обновить форму',
  'op.deleteForm': 'Удалить форму',
  'op.listSubmissions': 'Список сабмитов',
  'op.createSnapshot': 'Создать снапшот',
  'op.listSnapshots': 'Список снапшотов',
  'op.deleteSnapshot': 'Удалить снапшот',
  'op.createBuild': 'Создать сборку',
  'op.getBuild': 'Статус сборки',
  'op.listBuilds': 'Список сборок',

  'builds.title': 'Публикация',
  'builds.snapshots': 'Снапшоты',
  'builds.builds': 'Сборки',
  'builds.env': 'Среда',
  'builds.statusCol': 'Статус',
  'builds.snapshot.new': 'Новый снапшот',
  'builds.snapshot.name': 'Название',
  'builds.snapshot.none': 'Снапшотов нет — создайте первый',
  'builds.builds.none': 'Сборок ещё нет',
  'builds.createdAt': 'Дата',
  'builds.env.production': 'prod',
  'builds.env.development': 'dev',
  'builds.status.queued': 'В очереди',
  'builds.status.building': 'Сборка…',
  'builds.status.ready': 'Готово',
  'builds.status.failed': 'Ошибка',
  'builds.published': 'Опубликовано',
  'builds.rebuild': 'Пересобрать',
  'builds.log': 'Лог сборки',
  'builds.open': 'Открыть превью',
  'builds.current.prod': 'Текущий на prod',
  'builds.publish': 'Опубликовать на prod',
  'builds.publish.title': 'Публикация на production',
  'builds.publish.description': 'Снапшот «{name}» будет собран и опубликован в production. Действие публичное — продолжить?',
  'builds.publish.reveal': 'Введите PROD для подтверждения',
  'builds.publish.invalid': 'Введите PROD — публикация приостановлена',
  'builds.rollback': 'Откатить на prod',
  'builds.rollback.title': 'Откат на production',
  'builds.rollback.description': 'Снапшот «{name}» снова будет опубликован, он станет текущим на prod.',
  'builds.rollback.reveal': 'Введите PROD для подтверждения',
  'builds.publishError': 'Не удалось опубликовать: {detail}',
  'builds.delete.confirm': 'Удалить снапшот',
  'op.runtimeStatus': 'Статус рантайма',

  'result.count': '{n} шт.',
  'result.site.created': 'Создан «{name}»',
  'result.site.deleted': 'Сайт «{name}» удалён',
  'result.saved.v': 'Сохранено, версия {version}',
  'result.runtime.miss': 'Рантайм не отвечает',
} as const;

export type AdminStringKey = keyof typeof STRINGS;