/** Ключи admin-UI (ru-первичны; перевод расширяется ключами `en.*`). */

export const STRINGS = {
  'nav.dashboard': 'Обзор',
  'nav.sites': 'Сайты',
  'nav.pages': 'Страницы',
  'nav.contents': 'Контент',
  'nav.assets': 'Ассеты',
  'nav.routes': 'Роуты',
  'nav.forms': 'Формы',
  'nav.snapshots': 'Снапшоты',
  'nav.builds': 'Публикация',
  'nav.tokens': 'Токены',
  'nav.deps': 'Зависимости',
  'nav.allowlist': 'Allowlist',
  'nav.settings': 'Настройки',
  'nav.git': 'Git',

  'app.name': 'Liapoldus',

  'tab.settings': 'Настройки',
  'tab.close': 'Закрыть вкладку',
  'tab.new': 'Новая вкладка',
  'view.mode': 'Режим',
  'view.maintenance': 'Обслуживание',
  'view.editor': 'Редактор',
  'tab.section.components': 'Компоненты',
  'tab.section.infra': 'Инфраструктура',
  'tab.section.pages': 'Страницы',
  'tab.section.states': 'Состояния',
  'tab.section.base': 'База сайта',
  'tab.section.components.description':
    'IDE: редактор компонентов, реестр и история (R5; ручные уточнения Schema — R8).',
  'tab.section.infra.description':
    'Операции, эндпоинты и формы (R6): дескрипторы из БД + предпросмотр вызовов.',
  'tab.section.pages.description': 'Редактор страниц (реализуется в R9–R11).',
  'tab.section.states.description': 'Снапшоты, выпуск и откат (реализуется в R9–R13).',
  'tab.section.base.description': 'Site-settings, темы, шрифты, шаблоны (реализуется в R14).',
  'tab.maintenance.content': 'Контент',
  'tab.maintenance.forms': 'Формы+ответы',
  'tab.maintenance.media': 'Медиа',
  'tab.maintenance.content.description':
    'Редактор контента и переводов по schema (реализуется в R3/R5).',
  'tab.maintenance.forms.description': 'Список форм и ответы: сабмиты, экспорт CSV.',
  'tab.maintenance.media.description': 'Ассеты: грид, загрузка, «где используется».',
  'home.sites': 'Сайты',
  'home.settings': 'Системные настройки',
  'home.settingsHint': 'Настройки сервера и токен',

  'page.overview': 'Обзор',
  'page.overview.empty': 'Выберите объект в меню слева',

  'common.loading': 'Загрузка…',
  'common.error': 'Ошибка',
  'common.reload': 'Обновить',
  'common.close': 'Закрыть',
  'common.create': 'Создать',
  'common.cancel': 'Отмена',
  'common.delete': 'Удалить',
  'common.confirm': 'Подтвердить',
  'common.actions': 'Действия',
  'common.empty': 'Пока пусто',
  'common.required': 'Обязательно',

  'site.title': 'Сайты',
  'site.new': 'Создать сайт',
  'site.name': 'Название',
  'site.slug': 'Slug',
  'site.locale': 'Язык по умолчанию',
  'site.hosts': 'Хосты',
  'site.none': 'Сайтов пока нет',
  'site.open': 'Открыть',
  'site.delete.confirm': 'Удалить сайт',
  'site.notFound': 'Сайт не найден',
  'site.pages.page': 'Страница',
  'site.pages.testPath': 'Тестовый path (превью групп)',
  'site.sections': 'Разделы',

  'page.title': 'Страницы',
  'page.new': 'Создать страницу',
  'page.name': 'Название',
  'page.slug': 'Slug',
  'page.version': 'Версия',
  'page.none': 'Страниц пока нет',
  'page.open': 'Открыть',
  'page.delete.confirm': 'Удалить страницу',
  'page.editor.placeholder': 'Редактор дерева — в разработке (M1).',

  'content.title': 'Контент',
  'content.new': 'Создать item',
  'content.collection': 'Коллекция',
  'content.collection.all': 'Все коллекции',
  'content.id': 'ID',
  'content.fields': 'Поля',
  'content.fieldKey': 'Ключ',
  'content.fieldType': 'Тип',
  'content.fieldValue': 'Значение',
  'content.open': 'Открыть',
  'content.none': 'Контента пока нет',
  'content.delete.confirm': 'Удалить item',
  'content.base': 'Базовые поля',
  'content.baseHint': 'Язык по умолчанию ({locale}) — база для остальных локлей',
  'content.translations': 'Переводы',
  'content.addLocale': 'Добавить локаль',
  'content.locale': 'Локаль',
  'content.noTranslations': 'Переводов ещё нет',
  'content.save': 'Сохранить поля',
  'content.saved': 'Сохранено',
  'content.deleteTranslation.confirm': 'Удалить перевод',
  'content.invalidJson': 'Поле "{key}": невалидный JSON',
  'content.createError': 'Ошибка создания: {detail}',
  'content.addField': 'Добавить поле',
  'content.type.string': 'строка',
  'content.type.number': 'число',
  'content.type.boolean': 'bool',
  'content.type.json': 'json',
  'content.type.richtext': 'rich-text',
  'content.richtext.hint': 'rich-text поля редактируются встроенным редактором',
  'content.back': 'К списку',
  'content.language': 'Язык',
  'content.language.all': 'Все языки',
  'content.status.translated': 'Переведено',
  'content.status.missing': 'Не переведено',
  'content.status.count': 'Переведено на {n}',
  'content.status.languages': '{n} яз.',
  'content.title.column': 'Заголовок',
  'content.type.column': 'Тип',
  'content.language.column': 'Языки',
  'content.updatedAt': 'Изменён',
  'content.draftUnsaved': 'Не сохранено',
  'content.locale.new': 'Добавить перевод',
  'content.loadError': 'Ошибка загрузки контента',
  'content.translation.noFields': 'Перевод ещё пуст — недостающие поля будут показаны из базового языка',

  'assets.title': 'Ассеты',
  'assets.upload': 'Загрузить',
  'assets.uploading': 'Загрузка…',
  'assets.file': 'Файл',
  'assets.name': 'Название',
  'assets.type': 'Тип',
  'assets.size': 'Размер',
  'assets.none': 'Ассетов пока нет',
  'assets.open': 'Открыть файл',
  'assets.delete.confirm': 'Удалить ассет',
  'assets.uploadError': 'Ошибка загрузки: {detail}',
  'assets.picker.title': 'Библиотека ассетов',
  'assets.picker.search': 'Поиск',
  'assets.select': 'Выбрать ассет',
  'assets.clear': 'Сбросить',

  'route.title': 'Роуты',
  'route.new': 'Создать роут',
  'route.matcher': 'Matcher (regex)',
  'route.priority': 'Приоритет',
  'route.action': 'Действие',
  'route.action.renderPage': 'Показ страницы',
  'route.action.serveAsset': 'Выдача ассета',
  'route.action.redirect': 'Редирект',
  'route.target': 'Цель',
  'route.none': 'Роутов пока нет',
  'route.delete.confirm': 'Удалить роут',
  'route.back': 'К списку роутов',
  'route.edit': 'Редактировать',
  'route.save': 'Сохранить',
  'route.saved': 'Сохранено',
  'route.errors.matcherRequired': 'Укажите matcher',
  'route.errors.matcherRegex': 'Matcher — невалидный regex',
  'route.errors.matcherAnchored': 'Matcher должен быть якорным (^…$)',
  'route.errors.targetRequired': 'Укажите цель',
  'route.errors.statusRequired': 'redirect: выберите код ответа',
  'route.redirect.status': 'Код ответа',
  'route.redirect.keepQuery': 'Сохранить query',
  'route.warnings.duplicate': 'Matcher совпадает с существующим роутом',
  'route.warnings.prefix': 'Matcher пересекается с роутом {matcher}',

  'richText.toolbar.bold': 'Жирный',
  'richText.toolbar.italic': 'Курсив',
  'richText.toolbar.strike': 'Зачёркнутый',
  'richText.toolbar.code': 'Инлайн-код',
  'richText.toolbar.h1': 'Заголовок H1',
  'richText.toolbar.h2': 'Заголовок H2',
  'richText.toolbar.h3': 'Заголовок H3',
  'richText.toolbar.bulletList': 'Маркированный список',
  'richText.toolbar.orderedList': 'Нумерованный список',
  'richText.toolbar.blockquote': 'Цитата',
  'richText.toolbar.codeBlock': 'Блок кода',
  'richText.toolbar.hr': 'Разделитель',
  'richText.toolbar.link': 'Ссылка',
  'richText.toolbar.image': 'Изображение',
  'richText.link.placeholder': 'URL ссылки',
  'richText.link.apply': 'OK',
  'richText.slash.hint': '/ для команд',
  'richText.slash.noMatch': 'Нет команд для «{query}»',

  'form.title': 'Формы',
  'form.new': 'Создать форму',
  'form.name': 'Название',
  'form.formId': 'ID формы',
  'form.formIdHint': 'ID сгенерируется как form.<slug из названия>',
  'form.fields': 'Поля',
  'form.none': 'Форм пока нет',
  'form.open': 'Открыть',
  'form.delete.confirm': 'Удалить форму',
  'form.save': 'Сохранить форму',
  'form.saved': 'Сохранено',
  'form.definition': 'Определение (JSON)',
  'form.invalid': 'Ошибка определения',
  'form.back': 'К списку форм',
  'form.submissions': 'Сабмиты',
  'form.submissions.none': 'Сабмитов пока нет',
  'form.submissions.id': 'ID',
  'form.submissions.date': 'Дата',
  'form.submissions.payload': 'Полезная нагрузка',
  'form.submissions.export': 'Экспорт CSV',
  'form.submissions.delete.confirm': 'Удалить ответ',

  'media.title': 'Медиа',
  'media.none': 'Медиа пока нет',
  'media.search': 'Поиск',
  'media.filter': 'Тип',
  'media.filter.all': 'Все типы',
  'media.copyUrl': 'Копировать ссылку',
  'media.copied': 'URL скопирован',
  'media.usage': 'Где используется',
  'media.usage.none': 'Нигде не используется',
  'media.usage.contents': 'Контент',
  'media.usage.forms': 'Формы',
  'media.usage.close': 'Скрыть',

  'editor.title': 'Редактор',
  'editor.undo': 'Назад',
  'editor.redo': 'Вперёд',
  'editor.addChild': 'Добавить',
  'editor.delete': 'Удалить',
  'editor.up': 'Вверх',
  'editor.down': 'Вниз',
  'editor.props': 'Свойства',
  'editor.selectHint': 'Выберите элемент во вкладке',
  'editor.unknownType': 'Неизвестный тип: {type}',
  'editor.tree': 'Дерево',
  'editor.canvas': 'Канвас',
  'editor.container': 'Контейнер',
  'editor.saveNow': 'Сохранить',
  'editor.saved': 'Сохранено, v{version}',
  'editor.dirty': 'Есть несохранённые изменения',
  'editor.saving': 'Сохранение…',
  'editor.saved.failed': 'Не удалось сохранить',
  'editor.binding': 'Источник',
  'editor.binding.path': 'Путь к данным',
  'editor.binding.literal': 'Литерал',
  'editor.binding.content': 'Контент',
  'editor.binding.routeGroup': 'Группа роута',
  'editor.binding.query': 'Параметры запроса',
  'editor.binding.operation': 'Операция',
  'editor.binding.form': 'Форма',
  'field.error.type': 'Неверный тип значения',
  'field.error.enum': 'Значение не из списка',
  'field.error.range': 'Вне диапазона',

  'canvas.design': 'Дизайн',
  'canvas.preview': 'Превью',
  'preview.build': 'Собрать превью',
  'preview.building': 'Сборка…',
  'preview.ready': 'Превью готово',
  'preview.failed': 'Ошибка сборки: {error}',
  'preview.empty': 'Соберите превью, чтобы видеть опубликованную страницу',
  'preview.open': 'Открыть в новой вкладке',
  'preview.refresh': 'Обновить превью',

  'op.listSites': 'Список сайтов',
  'op.createSite': 'Создать сайт',
  'op.getSite': 'Информация о сайте',
  'op.updateSite': 'Обновить сайт',
  'op.deleteSite': 'Удалить сайт',
  'op.createPage': 'Создать страницу',
  'op.listPages': 'Список страниц',
  'op.getPage': 'Страница',
  'op.updatePage': 'Обновить страницу',
  'op.deletePage': 'Удалить страницу',
  'op.listContents': 'Список контента',
  'op.getContent': 'Контент',
  'op.createContent': 'Создать контент',
  'op.updateContent': 'Обновить контент',
  'op.deleteContent': 'Удалить контент',
  'op.putTranslation': 'Перевод сохранён',
  'op.deleteTranslation': 'Перевод удалён',
  'op.getContentLocales': 'Локали контента',
  'op.listAssets': 'Список ассетов',
  'op.uploadAsset': 'Загрузка ассета',
  'op.getAsset': 'Ассет',
  'op.deleteAsset': 'Удалить ассет',
  'op.listRoutes': 'Список роутов',
  'op.getRoute': 'Роут',
  'op.createRoute': 'Создать роут',
  'op.updateRoute': 'Обновить роут',
  'op.deleteRoute': 'Удалить роут',
  'op.listForms': 'Список форм',
  'op.createForm': 'Создать форму',
  'op.getForm': 'Форма',
  'op.updateForm': 'Обновить форму',
  'op.deleteForm': 'Удалить форму',
  'op.listSubmissions': 'Список сабмитов',
  'op.deleteSubmission': 'Удалить сабмиссию',
  'op.getAssetUsage': 'Ассет: где используется',
  'op.createSnapshot': 'Создать снапшот',
  'op.listSnapshots': 'Список снапшотов',
  'op.deleteSnapshot': 'Удалить снапшот',
  'op.createBuild': 'Создать сборку',
  'op.getBuild': 'Статус сборки',
  'op.listBuilds': 'Список сборок',

  'builds.title': 'Публикация',
  'builds.snapshots': 'Снапшоты',
  'builds.builds': 'Сборки',
  'builds.env': 'Среда',
  'builds.statusCol': 'Статус',
  'builds.snapshot.new': 'Новый снапшот',
  'builds.snapshot.name': 'Название',
  'builds.snapshot.none': 'Снапшотов нет — создайте первый',
  'builds.builds.none': 'Сборок ещё нет',
  'builds.createdAt': 'Дата',
  'builds.env.production': 'prod',
  'builds.env.development': 'dev',
  'builds.status.queued': 'В очереди',
  'builds.status.building': 'Сборка…',
  'builds.status.ready': 'Готово',
  'builds.status.failed': 'Ошибка',
  'builds.published': 'Опубликовано',
  'builds.rebuild': 'Пересобрать',
  'builds.log': 'Лог сборки',
  'builds.open': 'Открыть превью',
  'builds.current.prod': 'Текущий на prod',
  'builds.publish': 'Опубликовать на prod',
  'builds.publish.title': 'Публикация на production',
  'builds.publish.description': 'Снапшот «{name}» будет собран и опубликован в production. Действие публичное — продолжить?',
  'builds.publish.reveal': 'Введите PROD для подтверждения',
  'builds.publish.invalid': 'Введите PROD — публикация приостановлена',
  'builds.rollback': 'Откатить на prod',
  'builds.rollback.title': 'Откат на production',
  'builds.rollback.description': 'Снапшот «{name}» снова будет опубликован, он станет текущим на prod.',
  'builds.rollback.reveal': 'Введите PROD для подтверждения',
  'builds.publishError': 'Не удалось опубликовать: {detail}',
  'builds.delete.confirm': 'Удалить снапшот',
  'op.runtimeStatus': 'Статус рантайма',

  'git.title': 'Git',
  'git.branches': 'Ветки',
  'git.dev': 'dev',
  'git.main': 'main',
  'git.dirty': 'есть несохранённые изменения',
  'git.clean': 'чисто',
  'git.notInit': 'Репозиторий не инициализирован — сделайте первый коммит',
  'git.commit.new': 'Сообщение коммита',
  'git.commit.placeholder': 'Например: заголовок хедера',
  'git.commit.btn': 'Коммит',
  'git.publish': 'Опубликовать',
  'git.publish.title': 'Публикация на production',
  'git.publish.description': 'dev → main: состояние dev будет перебазировано и опубликовано на main. Действие публичное — продолжить?',
  'git.publish.reveal': 'Введите PROD для подтверждения',
  'git.publish.invalid': 'Введите PROD — публикация приостановлена',
  'git.commits': 'История (dev)',
  'git.commits.none': 'Коммитов пока нет',
  'git.restore': 'Восстановить',
  'git.restore.title': 'Восстановить состояние',
  'git.restore.description': 'Состояние БД будет перезаписано из коммита {short}. Текущее состояние сохранится safety-коммитом на dev — продолжить?',
  'git.restore.reveal': 'Введите RESTORE для подтверждения',
  'git.restore.invalid': 'Введите RESTORE — восстановление приостановлено',
  'git.rollback': 'Откатить',
  'git.rollback.title': 'Откат на production',
  'git.rollback.description': 'main будет перемотан на снапшот {name} ({short}). Текущий prod сохранится на dev — продолжить?',
  'git.rollback.reveal': 'Введите PROD для подтверждения',
  'git.sha': 'SHA',
  'git.message': 'Сообщение',
  'git.author': 'Автор',
  'git.date': 'Дата',
  'git.snapshots': 'Снапшоты (точки отката)',
  'git.snapshots.none': 'Публикаций пока нет',
  'git.current': 'текущий prod',
  'git.error': 'Ошибка: {detail}',
  'op.getGitOverview': 'Git: статус и история',
  'op.commitGit': 'Git: коммит',
  'op.publishGit': 'Git: публикация',
  'op.restoreGit': 'Git: восстановление',
  'op.rollbackGit': 'Git: откат',
  'op.getDashboard': 'Дашборд',
  'op.getSettings': 'Настройки',
  'op.getTokens': 'Токены: чтение набора',
  'op.updateTokens': 'Токены: сохранение набора',

  'op.listDependencies': 'Список зависимостей',
  'op.addDependency': 'Добавить зависимость',
  'op.removeDependency': 'Удалить зависимость',
  'op.resolveDependencies': 'Разрешить дерево зависимостей',
  'op.listAllowlist': 'Список правил allowlist',
  'op.addAllowlist': 'Добавить правило allowlist',
  'op.removeAllowlist': 'Удалить правило allowlist',
  'op.getCacheConfig': 'Кэш: чтение конфигурации',
  'op.updateCacheConfig': 'Кэш: обновление лимита',
  'op.evictCache': 'Кэш: очистка',
  'op.addDependency.result': 'Зависимость {name} добавлена',
  'op.addAllowlist.result': 'Правило {entry} добавлено',

  'deps.title': 'Зависимости',
  'deps.subtitle': 'NPM-пакеты сайта (spec §8). Версии разрешаются точным инстанцированием при снапшоте.',
  'deps.none': 'Зависимостей пока нет — добавьте пакет (например lodash ^4)',
  'deps.add': 'Добавить зависимость',
  'deps.name': 'Пакет',
  'deps.name.placeholder': 'lodash',
  'deps.spec': 'Диапазон версии',
  'deps.spec.placeholder': '^4',
  'deps.remove': 'Удалить',
  'deps.resolve': 'Разрешить граф',
  'deps.resolving': 'Разрешение…',
  'deps.resolve.error': 'Ошибка: {detail}',
  'deps.resolve.none': 'Граф пуст — нет объявленных зависимостей',
  'deps.loading': 'Загрузка…',
  'deps.error': 'Ошибка: {detail}',
  'deps.reload': 'Обновить',
  'deps.tree': 'Граф зависимостей',
  'deps.tree.hint': 'Полное рекурсивное дерево (BFS, hoisted-инстансы объединены). Клик по строке разворачивает её.',
  'deps.badge.hoisted': 'hoisted',
  'deps.badge.nested': 'nested',
  'deps.badge.peer': 'peer',
  'deps.tree.component': 'Версия: {version}',
  'deps.empty': 'Зависимостей пока нет',

  'deps.cache.title': 'Кэш',
  'deps.cache.hint': 'Лимит кэша тарболов в байтах (spec §11). 0 = без своего лимита.',
  'deps.cache.limit': 'Лимит, байт',
  'deps.cache.unset': 'Свой лимит не задан (0)',
  'deps.cache.save': 'Сохранить',
  'deps.cache.saved': 'Сохранено',
  'deps.cache.saving': 'Сохранение…',
  'deps.cache.failed': 'Ошибка: {detail}',
  'deps.cache.evict': 'Очистить кэш',
  'deps.cache.evicting': 'Очистка…',
  'deps.cache.evicted': 'Удалено {n} тарболов ({bytes} байт)',
  'deps.cache.evict.failed': 'Ошибка: {detail}',

  'allowlist.title': 'Allowlist',
  'allowlist.hint': 'Правила разрешённых пакетов (spec §5). Пустой список = разрешено всё.',
  'allowlist.entry': 'Правило',
  'allowlist.entry.placeholder': '@scope/* или lodash или *',
  'allowlist.add': 'Добавить правило',
  'allowlist.none': 'Правил пока нет — разрешены все пакеты',
  'allowlist.remove': 'Удалить',
  'allowlist.error': 'Ошибка: {detail}',
  'allowlist.reload': 'Обновить',
  'allowlist.loading': 'Загрузка…',

  'tokens.title': 'Токены',
  'tokens.saved': 'Сохранено',
  'tokens.saving': 'Сохранение…',
  'tokens.dirty': 'Есть несохранённые изменения',
  'tokens.failed': 'Не удалось сохранить: {detail}',
  'tokens.colors': 'Цвета',
  'tokens.colors.none': 'Цветов пока нет — добавьте роль (например accent, danger)',
  'tokens.color.add': 'Добавить цвет',
  'tokens.color.name': 'Роль',
  'tokens.color.light': 'Light',
  'tokens.color.dark': 'Dark',
  'tokens.color.picker': 'Палитра',
  'tokens.groups': 'Скалярные группы',
  'tokens.addValue': 'Добавить значение',
  'tokens.key': 'Ключ',
  'tokens.value': 'Значение',
  'tokens.remove': 'Удалить',
  'tokens.invalidColor': 'Невалидный цвет',
  'tokens.group.choose': 'Добавить в группу…',
  'tokens.group.typography': 'Типографика',
  'tokens.group.spacing': 'Отступы',
  'tokens.group.shadows': 'Тени',
  'tokens.group.borders': 'Границы',
  'tokens.group.breakpoints': 'Брейкпоинты',
  'tokens.group.zIndex': 'Z-индекс',
  'tokens.group.opacity': 'Прозрачность',
  'tokens.group.transitions': 'Переходы',
  'tokens.group.custom': 'Пользовательские',
  'tokens.preview': 'Превью',
  'tokens.preview.hint': 'Токены применяются как CSS-переменные префикса var(--lia-*)',

  'auth.login.title': 'Вход в админку',
  'auth.login.token': 'Токен',
  'auth.login.empty': 'Введите токен',
  'auth.login.invalid': 'Неверный токен',
  'auth.login.submit': 'Войти',
  'auth.login.hint': 'Возьмите токен из настроек сервера (LIAPOLDUS_ADMIN_TOKEN)',
  'auth.login.open': 'Токен не требуется (сервер без пароля)',
  'auth.logout': 'Выйти',

  'dashboard.runtime': 'Рантайм',
  'dashboard.runtime.ok': 'ok',
  'dashboard.runtime.degraded': 'требует внимания',
  'dashboard.runtime.noBuilds': 'нет публикаций',
  'dashboard.count.sites': 'Сайтов: {n}',
  'dashboard.count.builds': 'Сборок: {n}',
  'dashboard.count.snapshots': 'Снапшотов: {n}',
  'dashboard.empty.title': 'Создайте первый сайт',
  'dashboard.empty.text': 'Создайте сайт, добавьте страницы и опубликуйте сборку',
  'dashboard.empty.cta': 'Создать сайт',
  'dashboard.quick': 'Быстрые действия',
  'dashboard.selectSite': 'Выбрать сайт',
  'dashboard.sites': 'Сайты',
  'dashboard.sites.none': 'Сайтов пока нет',
  'dashboard.git.dev': 'dev',
  'dashboard.git.main': 'main',
  'dashboard.git.dirty': 'есть несохранённые',
  'dashboard.git.none': 'ещё не инициализирован',
  'dashboard.recentBuilds': 'Последние сборки',
  'dashboard.recentSnapshots': 'Последние снапшоты',
  'dashboard.recent.none': 'Пока пусто',
  'dashboard.none': 'Ничего не найдено',

  'settings.title': 'Настройки',
  'settings.adminToken': 'Admin-токен',
  'settings.defaultLocale': 'Локаль по умолчанию',
  'settings.redirectDefaultStatus': 'Код редиректа по умолчанию',
  'settings.version': 'Версия приложения',
  'settings.readonly': 'Управляется конфигурацией сервера',
  'settings.rotate': 'Новый токен',
  'settings.rotate.submit': 'Сохранить',
  'settings.rotate.saved': 'Токен обновлён',
  'settings.rotate.invalid': 'Токен не подходит',

  'site.edit': 'Редактировать',
  'site.edit.slugNote': 'Slug менять нельзя',
  'site.edit.save': 'Сохранить',
  'site.edit.saved': 'Сохранено',
  'site.edit.hosts': 'Хосты',
  'site.edit.addHost': 'Добавить хост',
  'site.edit.hostPlaceholder': 'example.com',

  'result.count': '{n} шт.',
  'result.assetUsage': 'Используется в {n}',
  'result.usedIn': 'Страниц: {n}',
  'result.site.created': 'Создан «{name}»',
  'result.site.deleted': 'Сайт «{name}» удалён',
  'result.saved.v': 'Сохранено, версия {version}',
  'result.saved.sha': 'Сохранено, {sha}',
  'result.runtime.miss': 'Рантайм не отвечает',

  'op.componentRegistry': 'Компоненты: реестр',
  'op.getComponent': 'Компонент',
  'op.createComponent': 'Создать компонент',
  'op.updateComponent': 'Компонент обновлён',
  'op.componentHistory': 'Компонент: история',
  'op.componentUsage': 'Компонент: где используется',
  'op.componentCommit': 'Компонент: коммит',
  'op.listOperations': 'Операции',
  'op.getOperation': 'Операция',
  'op.createOperation': 'Создать операцию',
  'op.updateOperation': 'Операция обновлена',
  'op.deleteOperation': 'Удалить операцию',
  'op.listEndpoints': 'Эндпоинты',
  'op.getEndpoint': 'Эндпоинт',
  'op.createEndpoint': 'Создать эндпоинт',
  'op.updateEndpoint': 'Эндпоинт обновлён',
  'op.deleteEndpoint': 'Удалить эндпоинт',

  'components.title': 'Компоненты',
  'components.registry': 'Реестр',
  'components.none': 'Компонентов пока нет',
  'components.new': 'Создать компонент',
  'components.create': 'Создать',
  'components.name': 'Название',
  'components.name.placeholder': 'Например: Card',
  'components.open': 'Открыть',
  'components.back': 'К списку',
  'components.kind': 'Тип',
  'components.version': 'Версия',
  'components.dirty': 'не сохранён',
  'components.committed': 'сохранён',
  'components.updatedAt': 'Изменён',
  'components.usage.none': 'Нигде не используется',
  'components.usage.pages': 'Страницы: {n}',
  'components.save': 'Сохранить',
  'components.saved': 'Сохранено',
  'components.dirty.title': 'Есть несохранённые изменения',
  'components.commit': 'Коммит',
  'components.commit.placeholder': 'Сообщение коммита',
  'components.committing': 'Коммит…',
  'components.committed.sha': 'Коммит {sha}',
  'components.commit.failed': 'Ошибка коммита: {detail}',
  'components.history': 'История',
  'components.history.none': 'Истории нет — сделайте первый коммит',
  'components.history.restore': 'Открыть',
  'components.history.readonly': 'Исходник на {short} (read-only)',
  'components.backToCurrent': 'Вернуться к текущей версии',
  'components.validation.ok': 'TSX валиден',
  'components.validation.error': 'Строка {line}: {message}',
  'components.validation.checking': 'Проверка…',
  'components.schema.title': 'Schema — авто-вывод из props',
  'components.schema.none': 'Props не выведены',
  'components.schema.required': 'обязательный',
  'components.schema.optional': 'необязательный',
  'components.slash.hint': '/ для сниппетов',
  'components.slash.none': 'Нет сниппетов для «{query}»',
  'components.slash.component': 'Компонент (default export)',
  'components.slash.section': 'Фрагмент: <section>',
  'components.slash.ref': 'Реф-плейсхолдер',
  'components.slash.binding': 'Binding-плейсхолдер',
  'components.saveShortcutHint': '⌘S — сохранить',

  'infra.operations': 'Операции',
  'infra.endpoints': 'Эндпоинты',
  'infra.forms': 'Формы',
  'infra.none.operations': 'Операций пока нет',
  'infra.none.endpoints': 'Эндпоинтов пока нет',
  'infra.operation.id': 'ID',
  'infra.operation.typeOp': 'Тип',
  'infra.operation.method': 'Метод',
  'infra.operation.path': 'Путь',
  'infra.operation.cache': 'Кэш',
  'infra.operation.provider': 'Провайдер',
  'infra.operation.scope': 'Scope',
  'infra.operation.resultType': 'Тип результата',
  'infra.operation.updatedAt': 'Изменён',
  'infra.newOperation': 'Создать операцию',
  'infra.editOperation': 'Изменить операцию',
  'infra.systemBadge': 'системная',
  'infra.editableBadge': 'настраиваемая',
  'infra.endpoint.id': 'ID',
  'infra.endpoint.method': 'Метод',
  'infra.endpoint.path': 'Путь',
  'infra.endpoint.operationId': 'Операция',
  'infra.endpoint.updatedAt': 'Изменён',
  'infra.newEndpoint': 'Создать эндпоинт',
  'infra.editEndpoint': 'Изменить эндпоинт',
  'infra.create': 'Создать',
  'infra.save': 'Сохранить',
  'infra.delete': 'Удалить',
  'infra.preview': 'Предпросмотр',
  'infra.preview.run': 'Выполнить',
  'infra.preview.mutation.confirm': 'Выполнить мутацию «{op}»?',
  'infra.preview.params.title': 'Параметры',
  'infra.preview.params.none': 'Параметров нет',
  'infra.preview.response.title': 'Ответ',
  'infra.preview.response.none': 'Выполните запрос, чтобы увидеть ответ',
  'infra.preview.run.pending': 'Выполнение…',
  'infra.path.invalid': 'Путь должен быть относительным (без // или http://)',
  'infra.form.fieldsReferences': 'Форма используется полями/кнопками. Редактирование определения — в разделе «Формы».',
} as const;

export type AdminStringKey = keyof typeof STRINGS;