// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/liapoldus/liapoldus/backend/internal/domain (interfaces: SiteRepository,PageRepository,SnapshotRepository)
//
// Generated by this command:
//
//	mockgen -package mocks -destination ../../tests/unit/mocks/repository.go github.com/liapoldus/liapoldus/backend/internal/domain SiteRepository,PageRepository,SnapshotRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/liapoldus/liapoldus/backend/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSiteRepository is a mock of SiteRepository interface.
type MockSiteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSiteRepositoryMockRecorder
	isgomock struct{}
}

// MockSiteRepositoryMockRecorder is the mock recorder for MockSiteRepository.
type MockSiteRepositoryMockRecorder struct {
	mock *MockSiteRepository
}

// NewMockSiteRepository creates a new mock instance.
func NewMockSiteRepository(ctrl *gomock.Controller) *MockSiteRepository {
	mock := &MockSiteRepository{ctrl: ctrl}
	mock.recorder = &MockSiteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSiteRepository) EXPECT() *MockSiteRepositoryMockRecorder {
	return m.recorder
}

// CreateSite mocks base method.
func (m *MockSiteRepository) CreateSite(arg0 context.Context, arg1 domain.Site) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSite indicates an expected call of CreateSite.
func (mr *MockSiteRepositoryMockRecorder) CreateSite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSite", reflect.TypeOf((*MockSiteRepository)(nil).CreateSite), arg0, arg1)
}

// GetSite mocks base method.
func (m *MockSiteRepository) GetSite(arg0 context.Context, arg1 string) (domain.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSite", arg0, arg1)
	ret0, _ := ret[0].(domain.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSite indicates an expected call of GetSite.
func (mr *MockSiteRepositoryMockRecorder) GetSite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSite", reflect.TypeOf((*MockSiteRepository)(nil).GetSite), arg0, arg1)
}

// GetSiteBySlug mocks base method.
func (m *MockSiteRepository) GetSiteBySlug(arg0 context.Context, arg1 string) (domain.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSiteBySlug", arg0, arg1)
	ret0, _ := ret[0].(domain.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiteBySlug indicates an expected call of GetSiteBySlug.
func (mr *MockSiteRepositoryMockRecorder) GetSiteBySlug(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteBySlug", reflect.TypeOf((*MockSiteRepository)(nil).GetSiteBySlug), arg0, arg1)
}

// MockPageRepository is a mock of PageRepository interface.
type MockPageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPageRepositoryMockRecorder
	isgomock struct{}
}

// MockPageRepositoryMockRecorder is the mock recorder for MockPageRepository.
type MockPageRepositoryMockRecorder struct {
	mock *MockPageRepository
}

// NewMockPageRepository creates a new mock instance.
func NewMockPageRepository(ctrl *gomock.Controller) *MockPageRepository {
	mock := &MockPageRepository{ctrl: ctrl}
	mock.recorder = &MockPageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPageRepository) EXPECT() *MockPageRepositoryMockRecorder {
	return m.recorder
}

// CreatePage mocks base method.
func (m *MockPageRepository) CreatePage(arg0 context.Context, arg1 domain.Page, arg2 domain.PageVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePage indicates an expected call of CreatePage.
func (mr *MockPageRepositoryMockRecorder) CreatePage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePage", reflect.TypeOf((*MockPageRepository)(nil).CreatePage), arg0, arg1, arg2)
}

// GetPage mocks base method.
func (m *MockPageRepository) GetPage(arg0 context.Context, arg1 string) (domain.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage", arg0, arg1)
	ret0, _ := ret[0].(domain.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPage indicates an expected call of GetPage.
func (mr *MockPageRepositoryMockRecorder) GetPage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockPageRepository)(nil).GetPage), arg0, arg1)
}

// ListPageVersions mocks base method.
func (m *MockPageRepository) ListPageVersions(arg0 context.Context, arg1 string) ([]domain.PageVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPageVersions", arg0, arg1)
	ret0, _ := ret[0].([]domain.PageVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPageVersions indicates an expected call of ListPageVersions.
func (mr *MockPageRepositoryMockRecorder) ListPageVersions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPageVersions", reflect.TypeOf((*MockPageRepository)(nil).ListPageVersions), arg0, arg1)
}

// ListPagesBySite mocks base method.
func (m *MockPageRepository) ListPagesBySite(arg0 context.Context, arg1 string) ([]domain.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPagesBySite", arg0, arg1)
	ret0, _ := ret[0].([]domain.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPagesBySite indicates an expected call of ListPagesBySite.
func (mr *MockPageRepositoryMockRecorder) ListPagesBySite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPagesBySite", reflect.TypeOf((*MockPageRepository)(nil).ListPagesBySite), arg0, arg1)
}

// UpdatePage mocks base method.
func (m *MockPageRepository) UpdatePage(arg0 context.Context, arg1 domain.Page, arg2 domain.PageVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePage indicates an expected call of UpdatePage.
func (mr *MockPageRepositoryMockRecorder) UpdatePage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePage", reflect.TypeOf((*MockPageRepository)(nil).UpdatePage), arg0, arg1, arg2)
}

// MockSnapshotRepository is a mock of SnapshotRepository interface.
type MockSnapshotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotRepositoryMockRecorder
	isgomock struct{}
}

// MockSnapshotRepositoryMockRecorder is the mock recorder for MockSnapshotRepository.
type MockSnapshotRepositoryMockRecorder struct {
	mock *MockSnapshotRepository
}

// NewMockSnapshotRepository creates a new mock instance.
func NewMockSnapshotRepository(ctrl *gomock.Controller) *MockSnapshotRepository {
	mock := &MockSnapshotRepository{ctrl: ctrl}
	mock.recorder = &MockSnapshotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotRepository) EXPECT() *MockSnapshotRepositoryMockRecorder {
	return m.recorder
}

// CreateSnapshot mocks base method.
func (m *MockSnapshotRepository) CreateSnapshot(arg0 context.Context, arg1 domain.Snapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockSnapshotRepositoryMockRecorder) CreateSnapshot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockSnapshotRepository)(nil).CreateSnapshot), arg0, arg1)
}

// GetSnapshot mocks base method.
func (m *MockSnapshotRepository) GetSnapshot(arg0 context.Context, arg1 string) (domain.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshot", arg0, arg1)
	ret0, _ := ret[0].(domain.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *MockSnapshotRepositoryMockRecorder) GetSnapshot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshot", reflect.TypeOf((*MockSnapshotRepository)(nil).GetSnapshot), arg0, arg1)
}

// ListSnapshotsBySite mocks base method.
func (m *MockSnapshotRepository) ListSnapshotsBySite(arg0 context.Context, arg1 string) ([]domain.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSnapshotsBySite", arg0, arg1)
	ret0, _ := ret[0].([]domain.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSnapshotsBySite indicates an expected call of ListSnapshotsBySite.
func (mr *MockSnapshotRepositoryMockRecorder) ListSnapshotsBySite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSnapshotsBySite", reflect.TypeOf((*MockSnapshotRepository)(nil).ListSnapshotsBySite), arg0, arg1)
}
