// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination ../../tests/unit/mocks/repository.go -package mocks --self_package github.com/liapoldus/liapoldus/backend
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/liapoldus/liapoldus/backend/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSiteRepository is a mock of SiteRepository interface.
type MockSiteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSiteRepositoryMockRecorder
	isgomock struct{}
}

// MockSiteRepositoryMockRecorder is the mock recorder for MockSiteRepository.
type MockSiteRepositoryMockRecorder struct {
	mock *MockSiteRepository
}

// NewMockSiteRepository creates a new mock instance.
func NewMockSiteRepository(ctrl *gomock.Controller) *MockSiteRepository {
	mock := &MockSiteRepository{ctrl: ctrl}
	mock.recorder = &MockSiteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSiteRepository) EXPECT() *MockSiteRepositoryMockRecorder {
	return m.recorder
}

// CreateSite mocks base method.
func (m *MockSiteRepository) CreateSite(arg0 context.Context, arg1 domain.Site) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSite indicates an expected call of CreateSite.
func (mr *MockSiteRepositoryMockRecorder) CreateSite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSite", reflect.TypeOf((*MockSiteRepository)(nil).CreateSite), arg0, arg1)
}

// DeleteSite mocks base method.
func (m *MockSiteRepository) DeleteSite(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSite indicates an expected call of DeleteSite.
func (mr *MockSiteRepositoryMockRecorder) DeleteSite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSite", reflect.TypeOf((*MockSiteRepository)(nil).DeleteSite), arg0, arg1)
}

// GetSite mocks base method.
func (m *MockSiteRepository) GetSite(arg0 context.Context, arg1 string) (domain.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSite", arg0, arg1)
	ret0, _ := ret[0].(domain.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSite indicates an expected call of GetSite.
func (mr *MockSiteRepositoryMockRecorder) GetSite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSite", reflect.TypeOf((*MockSiteRepository)(nil).GetSite), arg0, arg1)
}

// GetSiteBySlug mocks base method.
func (m *MockSiteRepository) GetSiteBySlug(arg0 context.Context, arg1 string) (domain.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSiteBySlug", arg0, arg1)
	ret0, _ := ret[0].(domain.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSiteBySlug indicates an expected call of GetSiteBySlug.
func (mr *MockSiteRepositoryMockRecorder) GetSiteBySlug(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteBySlug", reflect.TypeOf((*MockSiteRepository)(nil).GetSiteBySlug), arg0, arg1)
}

// ListSites mocks base method.
func (m *MockSiteRepository) ListSites(arg0 context.Context) ([]domain.Site, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSites", arg0)
	ret0, _ := ret[0].([]domain.Site)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSites indicates an expected call of ListSites.
func (mr *MockSiteRepositoryMockRecorder) ListSites(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSites", reflect.TypeOf((*MockSiteRepository)(nil).ListSites), arg0)
}

// UpdateSite mocks base method.
func (m *MockSiteRepository) UpdateSite(arg0 context.Context, arg1 domain.Site) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSite indicates an expected call of UpdateSite.
func (mr *MockSiteRepositoryMockRecorder) UpdateSite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSite", reflect.TypeOf((*MockSiteRepository)(nil).UpdateSite), arg0, arg1)
}

// MockPageRepository is a mock of PageRepository interface.
type MockPageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPageRepositoryMockRecorder
	isgomock struct{}
}

// MockPageRepositoryMockRecorder is the mock recorder for MockPageRepository.
type MockPageRepositoryMockRecorder struct {
	mock *MockPageRepository
}

// NewMockPageRepository creates a new mock instance.
func NewMockPageRepository(ctrl *gomock.Controller) *MockPageRepository {
	mock := &MockPageRepository{ctrl: ctrl}
	mock.recorder = &MockPageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPageRepository) EXPECT() *MockPageRepositoryMockRecorder {
	return m.recorder
}

// CreatePage mocks base method.
func (m *MockPageRepository) CreatePage(arg0 context.Context, arg1 domain.Page, arg2 domain.PageVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePage indicates an expected call of CreatePage.
func (mr *MockPageRepositoryMockRecorder) CreatePage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePage", reflect.TypeOf((*MockPageRepository)(nil).CreatePage), arg0, arg1, arg2)
}

// DeletePage mocks base method.
func (m *MockPageRepository) DeletePage(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePage indicates an expected call of DeletePage.
func (mr *MockPageRepositoryMockRecorder) DeletePage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePage", reflect.TypeOf((*MockPageRepository)(nil).DeletePage), arg0, arg1)
}

// GetPage mocks base method.
func (m *MockPageRepository) GetPage(arg0 context.Context, arg1 string) (domain.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage", arg0, arg1)
	ret0, _ := ret[0].(domain.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPage indicates an expected call of GetPage.
func (mr *MockPageRepositoryMockRecorder) GetPage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockPageRepository)(nil).GetPage), arg0, arg1)
}

// GetPageVersion mocks base method.
func (m *MockPageRepository) GetPageVersion(arg0 context.Context, arg1, arg2 string) (domain.PageVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPageVersion", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.PageVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPageVersion indicates an expected call of GetPageVersion.
func (mr *MockPageRepositoryMockRecorder) GetPageVersion(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPageVersion", reflect.TypeOf((*MockPageRepository)(nil).GetPageVersion), arg0, arg1, arg2)
}

// ListPageVersions mocks base method.
func (m *MockPageRepository) ListPageVersions(arg0 context.Context, arg1 string) ([]domain.PageVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPageVersions", arg0, arg1)
	ret0, _ := ret[0].([]domain.PageVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPageVersions indicates an expected call of ListPageVersions.
func (mr *MockPageRepositoryMockRecorder) ListPageVersions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPageVersions", reflect.TypeOf((*MockPageRepository)(nil).ListPageVersions), arg0, arg1)
}

// ListPagesBySite mocks base method.
func (m *MockPageRepository) ListPagesBySite(arg0 context.Context, arg1 string) ([]domain.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPagesBySite", arg0, arg1)
	ret0, _ := ret[0].([]domain.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPagesBySite indicates an expected call of ListPagesBySite.
func (mr *MockPageRepositoryMockRecorder) ListPagesBySite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPagesBySite", reflect.TypeOf((*MockPageRepository)(nil).ListPagesBySite), arg0, arg1)
}

// UpdatePage mocks base method.
func (m *MockPageRepository) UpdatePage(arg0 context.Context, arg1 domain.Page, arg2 domain.PageVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePage indicates an expected call of UpdatePage.
func (mr *MockPageRepositoryMockRecorder) UpdatePage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePage", reflect.TypeOf((*MockPageRepository)(nil).UpdatePage), arg0, arg1, arg2)
}

// MockSnapshotRepository is a mock of SnapshotRepository interface.
type MockSnapshotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotRepositoryMockRecorder
	isgomock struct{}
}

// MockSnapshotRepositoryMockRecorder is the mock recorder for MockSnapshotRepository.
type MockSnapshotRepositoryMockRecorder struct {
	mock *MockSnapshotRepository
}

// NewMockSnapshotRepository creates a new mock instance.
func NewMockSnapshotRepository(ctrl *gomock.Controller) *MockSnapshotRepository {
	mock := &MockSnapshotRepository{ctrl: ctrl}
	mock.recorder = &MockSnapshotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotRepository) EXPECT() *MockSnapshotRepositoryMockRecorder {
	return m.recorder
}

// CreateSnapshot mocks base method.
func (m *MockSnapshotRepository) CreateSnapshot(arg0 context.Context, arg1 domain.Snapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockSnapshotRepositoryMockRecorder) CreateSnapshot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockSnapshotRepository)(nil).CreateSnapshot), arg0, arg1)
}

// DeleteSnapshot mocks base method.
func (m *MockSnapshotRepository) DeleteSnapshot(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshot", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockSnapshotRepositoryMockRecorder) DeleteSnapshot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockSnapshotRepository)(nil).DeleteSnapshot), arg0, arg1)
}

// GetSnapshot mocks base method.
func (m *MockSnapshotRepository) GetSnapshot(arg0 context.Context, arg1 string) (domain.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshot", arg0, arg1)
	ret0, _ := ret[0].(domain.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *MockSnapshotRepositoryMockRecorder) GetSnapshot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshot", reflect.TypeOf((*MockSnapshotRepository)(nil).GetSnapshot), arg0, arg1)
}

// ListSnapshotsBySite mocks base method.
func (m *MockSnapshotRepository) ListSnapshotsBySite(arg0 context.Context, arg1 string) ([]domain.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSnapshotsBySite", arg0, arg1)
	ret0, _ := ret[0].([]domain.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSnapshotsBySite indicates an expected call of ListSnapshotsBySite.
func (mr *MockSnapshotRepositoryMockRecorder) ListSnapshotsBySite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSnapshotsBySite", reflect.TypeOf((*MockSnapshotRepository)(nil).ListSnapshotsBySite), arg0, arg1)
}

// MockContentRepository is a mock of ContentRepository interface.
type MockContentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContentRepositoryMockRecorder
	isgomock struct{}
}

// MockContentRepositoryMockRecorder is the mock recorder for MockContentRepository.
type MockContentRepositoryMockRecorder struct {
	mock *MockContentRepository
}

// NewMockContentRepository creates a new mock instance.
func NewMockContentRepository(ctrl *gomock.Controller) *MockContentRepository {
	mock := &MockContentRepository{ctrl: ctrl}
	mock.recorder = &MockContentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentRepository) EXPECT() *MockContentRepositoryMockRecorder {
	return m.recorder
}

// CreateContent mocks base method.
func (m *MockContentRepository) CreateContent(arg0 context.Context, arg1 domain.Content) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateContent indicates an expected call of CreateContent.
func (mr *MockContentRepositoryMockRecorder) CreateContent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContent", reflect.TypeOf((*MockContentRepository)(nil).CreateContent), arg0, arg1)
}

// DeleteContent mocks base method.
func (m *MockContentRepository) DeleteContent(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContent indicates an expected call of DeleteContent.
func (mr *MockContentRepositoryMockRecorder) DeleteContent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContent", reflect.TypeOf((*MockContentRepository)(nil).DeleteContent), arg0, arg1)
}

// GetContent mocks base method.
func (m *MockContentRepository) GetContent(arg0 context.Context, arg1 string) (domain.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", arg0, arg1)
	ret0, _ := ret[0].(domain.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockContentRepositoryMockRecorder) GetContent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockContentRepository)(nil).GetContent), arg0, arg1)
}

// GetContentsByIDs mocks base method.
func (m *MockContentRepository) GetContentsByIDs(arg0 context.Context, arg1 string, arg2 []string) (map[string]domain.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContentsByIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]domain.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContentsByIDs indicates an expected call of GetContentsByIDs.
func (mr *MockContentRepositoryMockRecorder) GetContentsByIDs(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContentsByIDs", reflect.TypeOf((*MockContentRepository)(nil).GetContentsByIDs), arg0, arg1, arg2)
}

// ListContentsBySite mocks base method.
func (m *MockContentRepository) ListContentsBySite(arg0 context.Context, arg1, arg2 string) ([]domain.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContentsBySite", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContentsBySite indicates an expected call of ListContentsBySite.
func (mr *MockContentRepositoryMockRecorder) ListContentsBySite(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContentsBySite", reflect.TypeOf((*MockContentRepository)(nil).ListContentsBySite), arg0, arg1, arg2)
}

// UpdateContent mocks base method.
func (m *MockContentRepository) UpdateContent(arg0 context.Context, arg1 domain.Content) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContent indicates an expected call of UpdateContent.
func (mr *MockContentRepositoryMockRecorder) UpdateContent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContent", reflect.TypeOf((*MockContentRepository)(nil).UpdateContent), arg0, arg1)
}

// MockAssetRepository is a mock of AssetRepository interface.
type MockAssetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAssetRepositoryMockRecorder
	isgomock struct{}
}

// MockAssetRepositoryMockRecorder is the mock recorder for MockAssetRepository.
type MockAssetRepositoryMockRecorder struct {
	mock *MockAssetRepository
}

// NewMockAssetRepository creates a new mock instance.
func NewMockAssetRepository(ctrl *gomock.Controller) *MockAssetRepository {
	mock := &MockAssetRepository{ctrl: ctrl}
	mock.recorder = &MockAssetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetRepository) EXPECT() *MockAssetRepositoryMockRecorder {
	return m.recorder
}

// CreateAsset mocks base method.
func (m *MockAssetRepository) CreateAsset(arg0 context.Context, arg1 domain.Asset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsset", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAsset indicates an expected call of CreateAsset.
func (mr *MockAssetRepositoryMockRecorder) CreateAsset(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsset", reflect.TypeOf((*MockAssetRepository)(nil).CreateAsset), arg0, arg1)
}

// DeleteAsset mocks base method.
func (m *MockAssetRepository) DeleteAsset(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAsset", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAsset indicates an expected call of DeleteAsset.
func (mr *MockAssetRepositoryMockRecorder) DeleteAsset(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsset", reflect.TypeOf((*MockAssetRepository)(nil).DeleteAsset), arg0, arg1)
}

// GetAsset mocks base method.
func (m *MockAssetRepository) GetAsset(arg0 context.Context, arg1 string) (domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAsset", arg0, arg1)
	ret0, _ := ret[0].(domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAsset indicates an expected call of GetAsset.
func (mr *MockAssetRepositoryMockRecorder) GetAsset(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAsset", reflect.TypeOf((*MockAssetRepository)(nil).GetAsset), arg0, arg1)
}

// ListAssetsBySite mocks base method.
func (m *MockAssetRepository) ListAssetsBySite(arg0 context.Context, arg1 string) ([]domain.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssetsBySite", arg0, arg1)
	ret0, _ := ret[0].([]domain.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAssetsBySite indicates an expected call of ListAssetsBySite.
func (mr *MockAssetRepositoryMockRecorder) ListAssetsBySite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssetsBySite", reflect.TypeOf((*MockAssetRepository)(nil).ListAssetsBySite), arg0, arg1)
}

// MockRouteRepository is a mock of RouteRepository interface.
type MockRouteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRouteRepositoryMockRecorder
	isgomock struct{}
}

// MockRouteRepositoryMockRecorder is the mock recorder for MockRouteRepository.
type MockRouteRepositoryMockRecorder struct {
	mock *MockRouteRepository
}

// NewMockRouteRepository creates a new mock instance.
func NewMockRouteRepository(ctrl *gomock.Controller) *MockRouteRepository {
	mock := &MockRouteRepository{ctrl: ctrl}
	mock.recorder = &MockRouteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteRepository) EXPECT() *MockRouteRepositoryMockRecorder {
	return m.recorder
}

// CreateRoute mocks base method.
func (m *MockRouteRepository) CreateRoute(arg0 context.Context, arg1 domain.Route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoute indicates an expected call of CreateRoute.
func (mr *MockRouteRepositoryMockRecorder) CreateRoute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoute", reflect.TypeOf((*MockRouteRepository)(nil).CreateRoute), arg0, arg1)
}

// DeleteRoute mocks base method.
func (m *MockRouteRepository) DeleteRoute(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoute", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoute indicates an expected call of DeleteRoute.
func (mr *MockRouteRepositoryMockRecorder) DeleteRoute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoute", reflect.TypeOf((*MockRouteRepository)(nil).DeleteRoute), arg0, arg1, arg2)
}

// GetRoute mocks base method.
func (m *MockRouteRepository) GetRoute(arg0 context.Context, arg1, arg2 string) (domain.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoute", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoute indicates an expected call of GetRoute.
func (mr *MockRouteRepositoryMockRecorder) GetRoute(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoute", reflect.TypeOf((*MockRouteRepository)(nil).GetRoute), arg0, arg1, arg2)
}

// ListRoutesBySite mocks base method.
func (m *MockRouteRepository) ListRoutesBySite(arg0 context.Context, arg1 string) ([]domain.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoutesBySite", arg0, arg1)
	ret0, _ := ret[0].([]domain.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoutesBySite indicates an expected call of ListRoutesBySite.
func (mr *MockRouteRepositoryMockRecorder) ListRoutesBySite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoutesBySite", reflect.TypeOf((*MockRouteRepository)(nil).ListRoutesBySite), arg0, arg1)
}

// UpdateRoute mocks base method.
func (m *MockRouteRepository) UpdateRoute(arg0 context.Context, arg1 domain.Route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoute indicates an expected call of UpdateRoute.
func (mr *MockRouteRepositoryMockRecorder) UpdateRoute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoute", reflect.TypeOf((*MockRouteRepository)(nil).UpdateRoute), arg0, arg1)
}

// MockFormRepository is a mock of FormRepository interface.
type MockFormRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFormRepositoryMockRecorder
	isgomock struct{}
}

// MockFormRepositoryMockRecorder is the mock recorder for MockFormRepository.
type MockFormRepositoryMockRecorder struct {
	mock *MockFormRepository
}

// NewMockFormRepository creates a new mock instance.
func NewMockFormRepository(ctrl *gomock.Controller) *MockFormRepository {
	mock := &MockFormRepository{ctrl: ctrl}
	mock.recorder = &MockFormRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormRepository) EXPECT() *MockFormRepositoryMockRecorder {
	return m.recorder
}

// CreateForm mocks base method.
func (m *MockFormRepository) CreateForm(arg0 context.Context, arg1 domain.Form) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForm", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateForm indicates an expected call of CreateForm.
func (mr *MockFormRepositoryMockRecorder) CreateForm(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForm", reflect.TypeOf((*MockFormRepository)(nil).CreateForm), arg0, arg1)
}

// CreateSubmission mocks base method.
func (m *MockFormRepository) CreateSubmission(arg0 context.Context, arg1 domain.Submission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubmission", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubmission indicates an expected call of CreateSubmission.
func (mr *MockFormRepositoryMockRecorder) CreateSubmission(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubmission", reflect.TypeOf((*MockFormRepository)(nil).CreateSubmission), arg0, arg1)
}

// DeleteForm mocks base method.
func (m *MockFormRepository) DeleteForm(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForm", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteForm indicates an expected call of DeleteForm.
func (mr *MockFormRepositoryMockRecorder) DeleteForm(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForm", reflect.TypeOf((*MockFormRepository)(nil).DeleteForm), arg0, arg1, arg2)
}

// GetForm mocks base method.
func (m *MockFormRepository) GetForm(arg0 context.Context, arg1, arg2 string) (domain.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForm", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForm indicates an expected call of GetForm.
func (mr *MockFormRepositoryMockRecorder) GetForm(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForm", reflect.TypeOf((*MockFormRepository)(nil).GetForm), arg0, arg1, arg2)
}

// ListFormsBySite mocks base method.
func (m *MockFormRepository) ListFormsBySite(arg0 context.Context, arg1 string) ([]domain.Form, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFormsBySite", arg0, arg1)
	ret0, _ := ret[0].([]domain.Form)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFormsBySite indicates an expected call of ListFormsBySite.
func (mr *MockFormRepositoryMockRecorder) ListFormsBySite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFormsBySite", reflect.TypeOf((*MockFormRepository)(nil).ListFormsBySite), arg0, arg1)
}

// ListSubmissionsByForm mocks base method.
func (m *MockFormRepository) ListSubmissionsByForm(arg0 context.Context, arg1, arg2 string) ([]domain.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubmissionsByForm", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubmissionsByForm indicates an expected call of ListSubmissionsByForm.
func (mr *MockFormRepositoryMockRecorder) ListSubmissionsByForm(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubmissionsByForm", reflect.TypeOf((*MockFormRepository)(nil).ListSubmissionsByForm), arg0, arg1, arg2)
}

// UpdateForm mocks base method.
func (m *MockFormRepository) UpdateForm(arg0 context.Context, arg1 domain.Form) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateForm", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateForm indicates an expected call of UpdateForm.
func (mr *MockFormRepositoryMockRecorder) UpdateForm(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateForm", reflect.TypeOf((*MockFormRepository)(nil).UpdateForm), arg0, arg1)
}
